# Use postgres/example user/password credentials
version: '3.3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=tavo
      - POSTGRES_DB=appcomfama   
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin2@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
  





# services:

#   postgres:
#      image: postgres:13
#      environment:
#        - POSTRGRES_DB=my_app
#        - POSTRGRES_DB_USER=tavo
#        - POSTRGRES_DB_PASSWORD=admin1234
#      ports:
#        - 5432:5432
#      volumes:
#        - ./postgres_data:/var/lib/postgresql/data



